# dependencies
  highlighter:      rouge
  kramdown:
    auto_ids:       true
  markdown:         kramdown

# permalinks
  permalink:        pretty

# server
  baseurl:          ""
  destination:      gh-pages
  encoding:         UTF-8
  exclude:          [assets/, gh-pages/, node_modules/]
  gems:
                    - jekyll-redirect-from
                    - jekyll-sitemap
  host:             0.0.0.0
  port:             9999
  source:           docs
  url:              http://daemonite.github.io/material

# social
  authors:          Daemonite
  description:      Daemonite's Material UI is a cross-platform and fully responsive front-end interface based on Google Material Design developed using Bootstrap 4.
  title:            Material

# vars
  cdn:
    jquery:         https://code.jquery.com/jquery-3.2.1.slim.min.js
    jquery_hash:    "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    md_font:        https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i
    md_icon:        https://fonts.googleapis.com/icon?family=Material+Icons
    popper:         https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.9.9/umd/popper.min.js
    popper_hash:    "sha256-c477vRLKQv1jt9o7w6TTBzFyFznTaZjoMLTDFi7Hlxc="
  current_version:  4.0.0-alpha.6
  download:
    source:         https://github.com/Daemonite/material/archive/v4.0.0-alpha.6.zip
    dist:           https://github.com/Daemonite/material/releases/download/v4.0.0-alpha.6/material-4.0.0-alpha.6-dist.zip
  id:
    navbar:         doc_navbar
    navdrawer:      doc_navdrawer
  repo:             https://github.com/Daemonite/material
